apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: {{ .Values.component_name }}
spec:
    refreshInterval: "5s"
    secretStoreRef: 
        name: vault-bakeend
        kind: ClusterSecretStore
    target:
        name: {{ .Values.component_name }}
    dataFrom:
    - extact:
        key: {{ .Values.component_name }}