apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.component_name }}
spec:
  refreshInterval: "5s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.component_name }}
  dataFrom:
    - extract:
        key: {{ .Values.component_name }}        # provider secret path / id in Vault
        # property: ""                            # optional: set if the provider secret stores JSON under a single property
        # decodingStrategy: Auto                    # Auto/Base64/None - pick what matches your provider
