{{ if .Values.schema.enabled }}
{{ - range .Values.schema.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.component_name }}-{{ . }}
spec:
  template: 
    spec: 
      containers: 
      - name: schema-load
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        envFrom: 
        - configMapRef:  
            name: {{ $.Values.component_name }}
        env:
          - name: SCHEMA_FILE
            value: db/{{ . }}.{{ .Values.schema.extension }}
      restartPolicy: Never
  backoffLimit: 3
{{ end }}
{{ end }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-app-user
spec: 
  template:
    spec:
      containers:
      - name: shcema-user-load
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        env:
        - name: DB_TYPE
          value: mysql 
        - name: APP_GIT_URL
          value: https://github.com/roboshop-devops-project-v3/shipping
        - name: DB_HOST
          value: mysql-dev.kommanuthala.store
        - name: DB_USER
          value: root 
        - name: DB_PASS
          value: RoboShop@1
        - name: SCHEMA_FILE
          value: db/app-user.sql 
      restartPolicy: Never
  backoffLimit: 3
---

apiVersion: batch/v1
kind: Job
metadata:
  name: shiping-schema
spec:
  template:
    spec:
      containers:
      - name: shcema-load
        image:  public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        env: 
        - name: DB_TYPE
          value: mysql 
        - name: APP_GIT_URL
          value: https://github.com/roboshop-devops-project-v3/shipping
        - name: DB_HOST
          value: mysql-dev.kommanuthala.store
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: RoboShop@1 
        - name: SCHEMA_FILE
          value: db/schema.sql 
      restartPolicy: Never  
  backoffLimit: 3
---

apiVersion: batch/v1
kind: Job
metadata: 
  name: shipping-master-data
spec:
  template:
    spec: 
      containers:
      - name: master-data
        image:  public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        env:
        - name: DB_TYPE
          value: mysql
        - name: APP_GIT_URL
          value: https://github.com/roboshop-devops-project-v3/shipping
        - name: DB_HOST
          value: mysql-dev.kommanuthala.store
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: RoboShop@1
        - name: SCHEMA_FILE
          value: db/master-data.sql 
      restartPolicy: Never
  backoffLimit: 3

