{{ if .Values.schema.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.component_name }}-schema
spec:
  template: 
    spec: 
      containers: 
      - name: schema-load
        image: 740279881161.dkr.ecr.us-east-1.amazonaws.com/{ .Values.component_name }}-schema
        envFrom: 
        - configMapRef:  
            name: {{ .Values.component_name }}
      restartPolicy: Never
  backoffLimit: 3
{{ end }}
